ibizaman/selfhostblocks

flake.lock
modules/blocks/postgresql.nix
test/modules/postgresql.nix
test/vm/postgresql.nix

fix ensure clauses in postgresql

---

modules/services/nextcloud-server.nix

 @ibizaman remove sops file dependency in nextcloud and ssl requirement

---

.github/workflows/lock-update.yaml
.github/workflows/test.yml

add flake lock update github action

---

demo/homeassistant/flake.lock
demo/homeassistant/flake.nix
demo/nextcloud/flake.lock
demo/nextcloud/flake.nix

make demos use selfhostblock provided inputs

---

modules/services/nextcloud-server.nix

I think this fixed a lot of my performance issues.

fix warning in nextcloud

---

docs/services.md
modules/services/nextcloud-server.nix
modules/services/nextcloud-server/docs/default.md

Add declarative configuration of LDAP in Nextcloud

---

demo/nextcloud/README.md
demo/nextcloud/flake.lock
demo/nextcloud/flake.nix
demo/nextcloud/secrets.yaml
modules/blocks/backup/docs/default.md
modules/services/nextcloud-server.nix
modules/services/nextcloud-server/docs/default.md

Add nextcloud integration with ldap to the manual and nextcloud demo.

---

modules/services/home-assistant.nix

This also updates the ldap option to match the Nextcloud one.

make home-assistant service work without ldap integration

---

modules/blocks/ssl.nix
modules/blocks/ssl/docs/default.md
test/vm/ssl.nix

- fix manual
- add more tests
- merge CA bundle with the one populated by NixOS

improve ssl block

---

docs/usage.md

It was missing a few instructions.

improve usage manual

---

modules/blocks/authelia.nix
modules/blocks/postgresql.nix
modules/services/home-assistant.nix
modules/services/nextcloud-server.nix
modules/services/nextcloud-server/docs/default.md
test/modules/postgresql.nix
test/vm/nextcloud.nix

add declarative sso integration for nextcloud

---

demo/homeassistant/flake.lock
demo/homeassistant/secrets.yaml
demo/nextcloud/README.md
demo/nextcloud/flake.lock
demo/nextcloud/flake.nix
demo/nextcloud/secrets.yaml

update nextcloud demo to have sso too

---

modules/blocks/ssl.nix
test/vm/ssl.nix

add extraDomains options for cert generation

---

modules/services/nextcloud-server.nix

fixes #131
Defaults to version 27.

allow to pick nextcloud package version

---

modules/blocks/vpn.nix

remove dependency of vpn.nix on sops-nix

---

modules/services/jellyfin.nix

remove dependency of jellyfin.nix on sops-nix

---

demo/homeassistant/README.md
demo/homeassistant/flake.lock
demo/homeassistant/flake.nix
demo/homeassistant/secrets.yaml

The format for the secret file has changed.

Update home-assistant demo

---

modules/services/nextcloud-server.nix
modules/services/nextcloud-server/docs/default.md

Add recommended settings for Nextcloud preview app

---

flake.nix
modules/services/grocy.nix
test/vm/grocy.nix

PR to add grocy as a service.
I think LDAP should be [relatively simple](https://www.reddit.com/r/grocy/comments/18avtb7/sso_tutorial/) to add, but couldn't find good information on SSO.
Will test this out for a while to make sure it really works before this can be merged.

Grocy service

---

.github/workflows/test.yml

Tests are failing on CI but work locally.

Reduce load on CI

---

lib/default.nix
modules/blocks/authelia.nix
modules/services/arr.nix
modules/services/home-assistant.nix
modules/services/vaultwarden.nix
test/modules/arr.nix
test/vm/lib.nix

I wasn't doing a recursive update so I was hiding the systemd.service configuration. -_-

fix arr setup

---

CHANGELOG.md
docs/usage.md
flake.nix

remove dependency on sops-nix

---

lib/default.nix
modules/blocks/ldap.nix
modules/blocks/restic.nix
modules/blocks/restic/docs/default.md
modules/contracts/backup.nix
modules/contracts/backup/docs/default.md
modules/services/arr.nix
modules/services/audiobookshelf.nix
modules/services/deluge.nix
modules/services/grocy.nix
modules/services/hledger.nix
modules/services/home-assistant.nix
modules/services/jellyfin.nix
modules/services/nextcloud-server.nix
modules/services/nextcloud-server/docs/default.md
modules/services/vaultwarden.nix
test/blocks/restic.nix
test/modules/arr.nix
test/services/vaultwarden.nix

This PR irons out the last issues with the backup contract and the Restic implementation.
I could check it works backing up files to a local folder and to Backblaze on my server.

more fixes to the backup contract

---

CHANGELOG.md
modules/blocks/authelia.nix
modules/services/nextcloud-server/docs/default.md
test/blocks/authelia.nix
test/common.nix
test/services/vaultwarden.nix

Looks like this is needed in the end, other we get into some flaky situations

Wait actively on ldap being ready

---

demo/nextcloud/flake.lock
demo/nextcloud/flake.nix

Hey, it's been a while. Noticed a couple of updates since last time I updated my SHB version and saw that they were also missing in the demo. 
I've been playing with the server quite a bit recently and SHB has been working great!
Cheers,
Sivert

Updated authelia config for nextcloud demo

---

docs/default.nix
docs/services.md
flake.nix
modules/blocks/nginx.nix
modules/services/forgejo.nix
modules/services/forgejo/docs/default.md
modules/services/jellyfin.nix
test/services/forgejo.nix

Has documentation and tests as well as LDAP and SSO support.

Add forgejo service

---

CHANGELOG.md
modules/blocks/ldap.nix
modules/contracts/secret.nix
modules/contracts/secret/docs/default.md
modules/contracts/secret/dummyModule.nix
test/blocks/authelia.nix
test/blocks/ldap.nix
test/common.nix
test/services/forgejo.nix
test/services/jellyfin.nix
test/services/nextcloud.nix

This makes the secret contract better (IMNSHO):
- Improves documentation, explains better the reasoning behind the contract.
- Makes it easier to create an option implementing the secret contract.

update secret contract

---

modules/blocks/ldap.nix

fix lldap backup

---

modules/blocks/restic.nix

The issue with activation script is the order is alphabetical, meaning the order the script is assembled is not really set in stone.
Here, because the script had a name starting with `restic`, it was ran before the `sops` secret generation script. And since the restic script was trying to use the secrets, it failed.
And if the activation script fails, you get a kernel panic.

Do not use activation script for script with dependencies

---

CHANGELOG.md
flake.nix
modules/blocks/monitoring/dashboards/SSL.json
modules/blocks/monitoring/rules.json
modules/blocks/ssl.nix
patches/prometheusnodecertexporter.nix
test/modules/nginx.nix

add alert when certs are close to expiring

---

docs/redirects.json
modules/services/nextcloud-server.nix

add memories nextcloud app

---

docs/redirects.json
modules/services/nextcloud-server/docs/default.md

add documentation for nextcloud memories and recognize apps

---

modules/services/home-assistant.nix

This was needed for Voice Assistant to correctly talk to Home Assistant.

fix internal url for voice assistant

---

modules/services/nextcloud-server.nix

Hi there, thank you for your project, it's always a great source for inspiration :).
I had issues with the current check for an existing storage mount. The script was always creating a new mount.
When i use `jq` for the check it works for me.
If you don't want to incorporate this change, please simply decline the PR; I don't require a merge.

Nextcloud server `externalStorage.userLocalMount` config existence check

---

flake.nix

as per its link, this issue appears resolved.

chore: remove insecure patch

---

CHANGELOG.md
demo/homeassistant/flake.lock
demo/homeassistant/flake.nix
demo/nextcloud/flake.lock
demo/nextcloud/flake.nix
docs/usage.md
flake.nix

This makes the setup for end users easier. See the usage diff.

provide patch nixpkgs function

---

modules/services/nextcloud-server.nix
test/services/nextcloud.nix

Until https://github.com/ibizaman/selfhostblocks/issues/476 is fixed

explicitly disable memories app in nextcloud

---

flake.nix
modules/services/jellyfin.nix
test/common.nix
test/services/arr.nix
test/services/audiobookshelf.nix
test/services/deluge.nix
test/services/grocy.nix
test/services/hledger.nix
test/services/home-assistant.nix
test/services/jellyfin.nix
test/services/vaultwarden.nix

Introduces declarative Jellyfin setup. It uses a new jellyfin-cli introduced in https://github.com/jellyfin/jellyfin/pull/14422.

declarative jellyfin setup

---

docs/redirects.json
flake.nix
modules/blocks/lldap.nix
modules/blocks/lldap/docs/default.md
patches/0001-lldap-lldap-0.6.1-unstable-2025-07-16.patch
patches/0002-lldap-add-options-to-set-important-secrets.patch
patches/0003-lldap-bootstrap-init-unstable-2025-07-16-lldap-add-e.patch
test/blocks/lldap.nix

add declarative lldap using secrets contract
